### ISSUE TITLE
[Dep-Update] Boost removed string_file.pp in 1.84.

### ISSUE THREAD

**Issue by Laikulo** [SoftFever/OrcaSlicer#3253]
### OrcaSlicer Version

v1.8.1

### OS version

Linux 6.6.6-1-default #1 SMP PREEMPT_DYNAMIC Mon Dec 11 09:46:39 UTC 2023 (a946a9f) x86_64 x86_64 x86_64 GNU/Linux

### Additional system information
```
System:
  Host: warforged Kernel: 6.6.6-1-default arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.27.10 Distro: openSUSE Tumbleweed 20231222
Machine:
  Type: Laptop System: Framework product: Laptop v: AB
    serial: <superuser required>
  Mobo: Framework model: FRANBMCP0B v: AB serial: <superuser required>
    UEFI: INSYDE v: 03.17 date: 10/27/2022
Battery:
  ID-1: BAT1 charge: 41.2 Wh (86.6%) condition: 47.6/55.0 Wh (86.5%)
CPU:
  Info: quad core 11th Gen Intel Core i7-1165G7 [MT MCP] speed (MHz): avg: 476
    min/max: 400/4700
Graphics:
  Device-1: Intel TigerLake-LP GT2 [Iris Xe Graphics] driver: i915 v: kernel
  Display: wayland server: X.org v: 1.21.1.9 with: Xwayland v: 23.2.2
    compositor: kwin_wayland driver: X: loaded: modesetting unloaded: fbdev,vesa
    dri: iris gpu: i915 resolution: 1805x1203
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 23.2.1
    renderer: Mesa Intel Xe Graphics (TGL GT2)
Network:
  Device-1: Intel Wi-Fi 6 AX210/AX211/AX411 160MHz driver: iwlwifi
Drives:
  Local Storage: total: 931.51 GiB used: 289.85 GiB (31.1%)
Info:
  Processes: 284 Uptime: 1h 48m Memory: total: 32 GiB note: est.
  available: 31.14 GiB used: 3.9 GiB (12.5%) Shell: Bash inxi: 3.3.31
```

### Printer

N/A

### How to reproduce

Compile with cmake with boost 1.84+ installed using BuildLinux.sh or cmake/make directly.

### Actual results
```
/home/aaron/vcs/OrcaSlicer/src/libslic3r/Format/bbs_3mf.cpp:26:10: fatal error: boost/filesystem/string_file.hpp: No such file or directory
   26 | #include <boost/filesystem/string_file.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Boost docs indicate that string_file and friends were removed in 1.84, and that io streams should be used instead: 
https://www.boost.org/doc/libs/1_84_0/libs/filesystem/doc/release_history.html

Appears to be used in four locations:
```
aaron@warforged:~/vcs/OrcaSlicer> rg boost/filesystem/string_file -l
src/slic3r/GUI/MediaPlayCtrl.cpp
src/slic3r/Utils/PresetUpdater.cpp
src/libslic3r/Format/bbs_3mf.cpp
src/libslic3r/Model.cpp
```

### Expected results

Compiles w/o error.

### Project file & Debug log uploads

N/A. There is no project file. 
```
aaron@warforged:~/vcs/OrcaSlicer> git describe --always --tag --long
v1.8.1-0-gbe1bd08
```

Make Output:
[make-output.log](https://github.com/SoftFever/OrcaSlicer/files/13759800/make-output.log)

### Checklist of files to include

- [X] Log file
- N/A Project file
